# This file contains all necessary information for this package
#   (when contained in a .star file)
# Plus, this file also doubles as compilation instruction
# To compile, just run "dotstar Package.yml"

# This file is written with the YAML language.
# All comments will be removed in the compiled package.
    
Compilation Information:
    Ignore files:
        # Which files should DotStar ignore when compiling?
        # You can use wildcards (such as *)
        - .git*
        - .vscode*
        - wget.star
Author information:
    Name: "joachimschmidt557"
    Company: ""
    Website: "https://github.com/joachimschmidt557"
    Email: ""
Package Information: 
    # The unique name of the package, preferably undercase letters, numbers
    # and hyphens only
    Name: "curl"

    # The "real name" of the package. Feel free to use any characters here
    Friendly Name: "cURL"

    # A short description
    Description: "command line tool and library for transferring data with URLs"

    # Version of the package
    Version: "7.56.1"

    # Versioning system
    Version System: "SemVer"

    # List of supported platforms
    Supported Platforms:
        #- macOS
        - Win32
        - Win64
        #- Linux
